- name: "Ansible setup"
  hosts: localhost
  connection: local 
  tasks:
  - name: "sync website"
    synchronize:
      src: site/
      dest: /var/www/default
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no